### ISSUE TITLE
listen udp port reports address already in use

### ISSUE THREAD

**Issue by ericwq** [ericwq/aprilsh#51]
server log
```
time=2024-02-19T15:49:17.074+08:00 level=INFO source=./server.go:1300 msg="user session end" user=root
time=2024-02-19T15:49:17.074+08:00 level=INFO source=./server.go:915 msg="stop listening on" port=60001
time=2024-02-19T15:49:36.574+08:00 level=INFO source=./server.go:890 msg="start listening on" port=60001 clientTERM=xterm-kitty
time=2024-02-19T15:49:36.574+08:00 level=INFO source=./server.go:940 msg="user session begin" user=root
time=2024-02-19T15:49:36.574+08:00 level=INFO source=./server.go:630 msg="start shell check user" user=ide gid=1000 HOME=/home/ide
time=2024-02-19T15:49:36.574+08:00 level=INFO source=./server.go:646 msg="start shell check env" env="[TERM=xterm-kitty PWD=/home/ide HOME=/home/ide USER=ide SHELL=/bin/ash TZ=Asia/Shanghai SSH_CLIENT=192.168.65.1 46404 22 SSH_CONNECTION=192.168.65.1 46404 172.17.0.3 22 NCURSES_NO_UTF8_ACS=1]"
time=2024-02-19T15:49:36.574+08:00 level=INFO source=./server.go:648 msg="start shell check command" commandPath=/bin/ash commandArgv=[-ash]
time=2024-02-19T15:49:36.575+08:00 level=INFO source=github.com/ericwq/aprilsh/network/network.go:756 msg="#recvOne server now attached to client" localAddr=[::]:60001 remoteAddr=192.168.65.1:27208 hasRemoteAddr=true
time=2024-02-19T15:49:36.575+08:00 level=DEBUG source=github.com/ericwq/aprilsh/network/network.go:627 msg="go messsage" i=0 localAddr=[::]:60001 remoteAddr=192.168.65.1:27208 payload=46 hasRemoteAddr=true
time=2024-02-19T15:49:36.575+08:00 level=DEBUG source=./server.go:1010 msg=mainLoop port=60001 network.WaitTime=0 complete.WaitTime=9223372036854775807 timeout=0
time=2024-02-19T15:49:36.575+08:00 level=DEBUG source=github.com/ericwq/aprilsh/network/transport.go:245 msg="got message" NewNum=1 OldNum=0 AckNum=0 throwawayNum=0 port=60001
time=2024-02-19T15:49:36.575+08:00 level=DEBUG source=github.com/ericwq/aprilsh/network/transport.go:347 msg="got message" receivedState=(0,1,) AckNum=1 pendingDataAck=true diffLength=9
time=2024-02-19T15:49:39.576+08:00 level=DEBUG source=github.com/ericwq/aprilsh/network/network.go:627 msg="go messsage" i=0 localAddr=[::]:60001 remoteAddr=192.168.65.1:27208 payload=45 hasRemoteAddr=true
time=2024-02-19T15:49:42.580+08:00 level=DEBUG source=github.com/ericwq/aprilsh/network/network.go:627 msg="go messsage" i=0 localAddr=[::]:60001 remoteAddr=192.168.65.1:27208 payload=49 hasRemoteAddr=true
time=2024-02-19T15:49:51.578+08:00 level=WARN source=./server.go:896 msg="startShell fail" error="pipe read: i/o timeout"
time=2024-02-19T16:01:11.534+08:00 level=WARN source=github.com/ericwq/aprilsh/network/network.go:503 msg="#tryBind listen" address=<nil> error="listen udp :60001: bind: address already in use"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x55802d6d8b4e]

goroutine 11 [running]:
github.com/ericwq/aprilsh/network.(*Connection).getKey(...)
        github.com/ericwq/aprilsh/network/network.go:857
github.com/ericwq/aprilsh/network.(*Transport[...]).GetKey(...)
        github.com/ericwq/aprilsh/network/transport.go:205
main.runWorker(0xc0000000c0, 0xc000072240, 0x0?)
        ./server.go:829 +0x1ee
main.(*mainSrv).run.func2(0x0?, 0x0?, 0x0?)
        ./server.go:1552 +0x24
created by main.(*mainSrv).run in goroutine 19
        ./server.go:1551 +0xa25
```

**Comment by ericwq** [comment]
another crash log.
```
time=2024-02-20T14:00:51.699+08:00 level=INFO source=/home/ide/develop/aprilsh/frontend/server/server.go:890 msg="start listening on" port=60001 clientTERM=xterm-kitty
time=2024-02-20T14:00:51.699+08:00 level=INFO source=/home/ide/develop/aprilsh/frontend/server/server.go:940 msg="user session begin" user=root
time=2024-02-20T14:00:51.700+08:00 level=INFO source=/home/ide/develop/aprilsh/frontend/server/server.go:630 msg="start shell check user" user=ide gid=1000 HOME=/home/ide
time=2024-02-20T14:00:51.700+08:00 level=INFO source=/home/ide/develop/aprilsh/frontend/server/server.go:646 msg="start shell check env" env="[TERM=xterm-kitty PWD=/home/ide HOME=/home/ide USER=ide SHELL=/bin/ash TZ=Asia/Shanghai SSH_CLIENT=192.168.65.1 46671 22 SSH_CONNECTION=192.168.65.1 46671 172.17.0.3 22 NCURSES_NO_UTF8_ACS=1]"
time=2024-02-20T14:00:51.700+08:00 level=INFO source=/home/ide/develop/aprilsh/frontend/server/server.go:648 msg="start shell check command" commandPath=/bin/ash commandArgv=[-ash]
time=2024-02-20T14:00:51.702+08:00 level=DEBUG source=/home/ide/develop/aprilsh/frontend/server/server.go:1010 msg=mainLoop port=60001 network.WaitTime=32767 complete.WaitTime=9223372036854775807 timeout=32767
time=2024-02-20T14:00:51.702+08:00 level=DEBUG source=/home/ide/develop/aprilsh/frontend/server/server.go:1160 msg="output from host" arise=master ouput="Welcome to Alpine!\r\n\r\nThe Alpine Wiki contains a large amount of how-to guides and general\r\ninformation about administrating Alpine systems.\r\nSee <https://wiki.alpinelinux.org/>.\r\n\r\nYou can setup the system with the command: setup-alpine\r\n\r\nYou may change this message by editing /etc/motd.\r\n\r\n" input=""
time=2024-02-20T14:00:51.702+08:00 level=DEBUG source=/home/ide/develop/aprilsh/frontend/server/server.go:1010 msg=mainLoop port=60001 network.WaitTime=32767 complete.WaitTime=9223372036854775807 timeout=32767
time=2024-02-20T14:00:51.710+08:00 level=DEBUG source=/home/ide/develop/aprilsh/frontend/server/server.go:1160 msg="output from host" arise=master ouput="\x1b]0;apsh ide@localhost:60001\a" input=""
time=2024-02-20T14:00:51.710+08:00 level=DEBUG source=/home/ide/develop/aprilsh/frontend/server/server.go:1010 msg=mainLoop port=60001 network.WaitTime=32767 complete.WaitTime=9223372036854775807 timeout=32767
time=2024-02-20T14:01:06.704+08:00 level=WARN source=/home/ide/develop/aprilsh/frontend/server/server.go:896 msg="startShell fail" error="pipe read: i/o timeout"
time=2024-02-20T14:01:06.704+08:00 level=WARN source=/home/ide/develop/aprilsh/frontend/server/server.go:1152 msg=shutdown from="read file failed" port=60001
time=2024-02-20T14:01:06.704+08:00 level=WARN source=/home/ide/develop/aprilsh/frontend/server/server.go:1257 msg="No connection within x seconds" seconds=15 timeout=shutdown port=60001
time=2024-02-20T14:01:06.705+08:00 level=WARN source=/home/ide/develop/aprilsh/network/network.go:503 msg="#tryBind listen" address=<nil> error="listen udp :60001: bind: address already in use"
time=2024-02-20T14:01:06.705+08:00 level=INFO source=/home/ide/develop/aprilsh/frontend/server/server.go:1300 msg="user session end" user=root
time=2024-02-20T14:01:06.705+08:00 level=INFO source=/home/ide/develop/aprilsh/frontend/server/server.go:915 msg="stop listening on" port=60001
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6808f1]

goroutine 106 [running]:
github.com/ericwq/aprilsh/network.(*Connection).getKey(...)
	/home/ide/develop/aprilsh/network/network.go:857
github.com/ericwq/aprilsh/network.(*Transport[...]).GetKey(...)
	/home/ide/develop/aprilsh/network/transport.go:205
main.runWorker(0xc000000240, 0xc000070120, 0xc0005897d0?)
	/home/ide/develop/aprilsh/frontend/server/server.go:829 +0x231
main.(*mainSrv).run.func2(0x0?, 0x4000?, 0xc000589798?)
	/home/ide/develop/aprilsh/frontend/server/server.go:1559 +0x2e
created by main.(*mainSrv).run in goroutine 36
	/home/ide/develop/aprilsh/frontend/server/server.go:1558 +0xbd6
```

**Comment by ericwq** [comment]
both crash is caused by 'address already in use'

**Comment by ericwq** [comment]
check available port before listening. verified
