### ISSUE TITLE
fix failed test for frontend/client package

### ISSUE THREAD

**Issue by ericwq** [ericwq/aprilsh#61]

**Comment by ericwq** [comment]
start with:
```
ide@openrc-nvide:~/develop/aprilsh/frontend/client $ go test -v
=== RUN   TestPrintColors
=== RUN   TestPrintColors/lookup_terminfo_failed
=== RUN   TestPrintColors/TERM_is_empty
=== RUN   TestPrintColors/TERM_doesn't_exit
=== RUN   TestPrintColors/normal_found
=== RUN   TestPrintColors/dynamic_not_found
--- PASS: TestPrintColors (0.00s)
    --- PASS: TestPrintColors/lookup_terminfo_failed (0.00s)
    --- PASS: TestPrintColors/TERM_is_empty (0.00s)
    --- PASS: TestPrintColors/TERM_doesn't_exit (0.00s)
    --- PASS: TestPrintColors/normal_found (0.00s)
    --- PASS: TestPrintColors/dynamic_not_found (0.00s)
=== RUN   TestMainRun_Parameters
=== RUN   TestMainRun_Parameters/no_parameters
--- FAIL: TestMainRun_Parameters (0.00s)
    --- FAIL: TestMainRun_Parameters/no_parameters (0.00s)
panic: apsh flag redefined: v [recovered]
        panic: apsh flag redefined: v

goroutine 30 [running]:
testing.tRunner.func1.2({0x7e3380, 0xc000030480})
        /usr/lib/go/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
        /usr/lib/go/src/testing/testing.go:1548 +0x397
panic({0x7e3380?, 0xc000030480?})
        /usr/lib/go/src/runtime/panic.go:914 +0x21f
flag.(*FlagSet).Var(0xc0000d00e0, {0x91c430, 0xc0000ca2c0}, {0x877003, 0x1}, {0x880ba4, 0x19})
        /usr/lib/go/src/flag/flag.go:1028 +0x3a5
flag.(*FlagSet).BoolVar(...)
        /usr/lib/go/src/flag/flag.go:749
github.com/ericwq/aprilsh/frontend/client.parseFlags({0x8773c7, 0x4}, {0xc0000303e0, 0x0, 0x0})
        /home/ide/develop/aprilsh/frontend/client/client.go:108 +0x278
github.com/ericwq/aprilsh/frontend/client.main()
        /home/ide/develop/aprilsh/frontend/client/client.go:1136 +0x68
github.com/ericwq/aprilsh/frontend/client.TestMainRun_Parameters.func1(0xc000154340)
        /home/ide/develop/aprilsh/frontend/client/client_test.go:169 +0xcf
testing.tRunner(0xc000154340, 0xc0000303f0)
        /usr/lib/go/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 29
        /usr/lib/go/src/testing/testing.go:1648 +0x3ad
exit status 2
FAIL    github.com/ericwq/aprilsh/frontend/client       0.011s
```

**Comment by ericwq** [comment]
```
ide@openrc-nvide:~/develop/aprilsh/frontend/client $ go test -cover . -args -test.gocoverdir=./coverage/unit
ok      github.com/ericwq/aprilsh/frontend/client       0.026s  coverage: 15.6% of statements
ide@openrc-nvide:~/develop/aprilsh/frontend/client $ go tool covdata percent -i=./coverage/unit,./coverage/int
        github.com/ericwq/aprilsh/frontend/client               coverage: 66.8% of statements
```

**Comment by ericwq** [comment]
on linux.
```
ide@openrc-nvide:~/develop/aprilsh/frontend/client $ go test -cover . -args -test.gocoverdir=./coverage/unit
ok      github.com/ericwq/aprilsh/frontend/client       0.027s  coverage: 23.6% of statements
```
on mac.
```
qiwang@Qi15Pro client % go test -cover . -args -test.gocoverdir=./coverage/unit
ok  	github.com/ericwq/aprilsh/frontend/client	0.235s	coverage: 26.7% of statements
```

**Comment by ericwq** [comment]
```
qiwang@gauss client % go test -cover . -args -test.gocoverdir=./coverage/unit
ok      github.com/ericwq/aprilsh/frontend/client       1.233s  coverage: 26.3% of statements
qiwang@gauss client % go tool covdata percent -i=./coverage/unit,./coverage/int
        github.com/ericwq/aprilsh/frontend/client               coverage: 75.0% of statements
```

**Comment by ericwq** [comment]
close this issue for the time being.
```
qiwang@gauss client % go test -cover . -args -test.gocoverdir=./coverage/unit
ok      github.com/ericwq/aprilsh/frontend/client       1.499s  coverage: 26.6% of statements
qiwang@gauss client % go tool covdata percent -i=./coverage/unit,./coverage/int
        github.com/ericwq/aprilsh/frontend/client               coverage: 75.0% of statements
```
