### ISSUE TITLE
fix failed test for network package

### ISSUE THREAD

**Issue by ericwq** [ericwq/aprilsh#66]
for darwin platform, the network package report:
```
qiwang@Qi15Pro network % go test -cover
--- FAIL: TestConnectionReadWrite (0.00s)
    network_test.go:293: "connection read/write" expect "a good news from udp client.", got ""
    network_test.go:293: "connection read/write" expect "天下风云出我辈，一入江湖岁月催。", got ""
--- FAIL: TestSendBranch (0.04s)
    network_test.go:787: "detect server detached from client" client send
        "detect server detached from client" to server, server got
        ""
    network_test.go:803: "detect server detached from client" expect log
        "#send server now detached from client", got
        ""
    network_test.go:809: "detect server detached from client" client receive
        "detect server detached from client" from server, client got
        ""
--- FAIL: TestRecvCongestionPacket (0.02s)
    network_test.go:1062: "receive congestion packet branch" expect
        "#recvOne received explicit congestion notification", got
        ""
--- FAIL: TestRecvSRTT (0.22s)
    network_test.go:1128: "receive packet to calculate SRTT/RTTVAR" expect "0 round from server to client", got ""
    network_test.go:1128: "receive packet to calculate SRTT/RTTVAR" expect "1 round from server to client", got ""
    network_test.go:1128: "receive packet to calculate SRTT/RTTVAR" expect "2 round from server to client", got ""
    network_test.go:1128: "receive packet to calculate SRTT/RTTVAR" expect "3 round from server to client", got ""
    network_test.go:1128: "receive packet to calculate SRTT/RTTVAR" expect "4 round from server to client", got ""
    network_test.go:1128: "receive packet to calculate SRTT/RTTVAR" expect "5 round from server to client", got ""
    network_test.go:1128: "receive packet to calculate SRTT/RTTVAR" expect "6 round from server to client", got ""
    network_test.go:1128: "receive packet to calculate SRTT/RTTVAR" expect "7 round from server to client", got ""
    network_test.go:1128: "receive packet to calculate SRTT/RTTVAR" expect "8 round from server to client", got ""
    network_test.go:1128: "receive packet to calculate SRTT/RTTVAR" expect "9 round from server to client", got ""
    network_test.go:1133: "receive packet to calculate SRTT/RTTVAR" RTTHit=false SRTT=1000.000000, RTTVAR=500.000000
    network_test.go:1138: "receive packet to calculate SRTT/RTTVAR" expect timeout 50, got 1000
--- FAIL: TestConnectionRecvSeqFail (0.00s)
    network_test.go:1223: "connection recv seq fail" expect "first message.", got ""
    network_test.go:1229: "connection recv seq fail" expect
        received explicit out-of-order packets, got
        time=2024-03-11T11:26:45.674+08:00 level=DEBUG source=/Users/qiwang/dev/aprilsh/network/network.go:469 msg=dialUDP pid=17890 ip=localhost port=60800 localAddr=[::1]:55971 remoteAddr=[::1]:60800

--- FAIL: TestSenderSendEmptyAckShutdown (0.02s)
    sender_test.go:408: #test recv repeat expect 18446744073709551615, got 0
    sender_test.go:409: #test receivedState length=1
--- FAIL: TestSenderSendToReceiverShutdown (0.02s)
    sender_test.go:528: #test recv repeat expect 18446744073709551615, got 0
--- FAIL: TestSenderTickVerify (0.09s)
    sender_test.go:645: #test client send "Keystroke:\"first mock input.\", Resize:, size=17" to server, server receive "Keystroke:\"\", Resize:, size=0" from client
    sender_test.go:654: #TestSenderTickVerify expect contains "tick Warning, round-trip Instruction verification failed", can't find it
    sender_test.go:654: #TestSenderTickVerify expect contains "tick Warning, target state Instruction verification failed", can't find it
--- FAIL: TestSenderSendInterval (0.12s)
    sender_test.go:693: #test sendInterval expect "0 round from server to client", got ""
    sender_test.go:693: #test sendInterval expect "1 round from server to client", got ""
    sender_test.go:693: #test sendInterval expect "2 round from server to client", got ""
    sender_test.go:693: #test sendInterval expect "3 round from server to client", got ""
    sender_test.go:693: #test sendInterval expect "4 round from server to client", got ""
    sender_test.go:693: #test sendInterval expect "5 round from server to client", got ""
    sender_test.go:693: #test sendInterval expect "6 round from server to client", got ""
    sender_test.go:693: #test sendInterval expect "7 round from server to client", got ""
    sender_test.go:693: #test sendInterval expect "8 round from server to client", got ""
    sender_test.go:693: #test sendInterval expect "9 round from server to client", got ""
    sender_test.go:701: #test sendInterval expect interval 250 < 20
--- FAIL: TestTransportClientSend (0.09s)
    transport_test.go:68: #test client send "Keystroke:\"Test client send and server empty ack.\", Resize:, size=38" to server, server receive "Keystroke:\"\", Resize:, size=0" from client
    transport_test.go:76: #test client sentStates expect first num 1, got 0
--- FAIL: TestTransportServerSend (0.08s)
    transport_test.go:124: #test server send expect remote address <nil>, got nil
--- FAIL: TestTransportRecvVersionError (0.02s)
    transport_test.go:226: #test recv error expect "aprilsh protocol version mismatch.", got "i/o timeout"
--- FAIL: TestTransportRecvRepeat (0.07s)
panic: runtime error: index out of range [1] with length 1 [recovered]
        panic: runtime error: index out of range [1] with length 1

goroutine 226 [running]:
testing.tRunner.func1.2({0x100394180, 0xc00001a138})
        /usr/local/go/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1548 +0x397
panic({0x100394180?, 0xc00001a138?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/ericwq/aprilsh/network.TestTransportRecvRepeat(0xc0006011e0)
        /Users/qiwang/dev/aprilsh/network/transport_test.go:263 +0x625
testing.tRunner(0xc0006011e0, 0x1003d1638)
        /usr/local/go/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
        /usr/local/go/src/testing/testing.go:1648 +0x3ad
exit status 2
FAIL    github.com/ericwq/aprilsh/network       4.876s
qiwang@Qi15Pro network %
```

**Comment by ericwq** [comment]
for linux the network package is ready.
```
ide@openrc-nvide:~/develop/aprilsh/network $ go test -cover
PASS
coverage: 100.0% of statements
ok      github.com/ericwq/aprilsh/network       2.272s
```

**Comment by ericwq** [comment]
for linux:
```
ide@openrc-nvide:~/develop/aprilsh/network $ go test -cover .
ok      github.com/ericwq/aprilsh/network       2.475s  coverage: 100.0% of statements
```
for macOS:
```
qiwang@gauss network % go test -cover .
ok  	github.com/ericwq/aprilsh/network	2.632s	coverage: 99.4% of statements
```
